server {
    listen 80;
    listen [::]:80;

    server_name hutei.net;

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    http2 on;

    server_name hutei.net;

    ssl_certificate /etc/letsencrypt/live/hutei.net/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/hutei.net/privkey.pem;

    root /usr/share/nginx/html;
    index hutei.html;

    location / {
        try_files /hutei.html =404;
    }
}

server {
    listen 80;
    listen [::]:80;

    server_name dash.hutei.net;

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    http2 on;

    server_name dash.hutei.net;

    ssl_certificate /etc/letsencrypt/live/hutei.net-0001/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/hutei.net-0001/privkey.pem;

    default_type text/plain;
    return 200 "В розробці\n";
}

server {
    listen 80;
    listen [::]:80;

    server_name ukubuka.net;

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    http2 on;

    server_name ukubuka.net;

    ssl_certificate /etc/letsencrypt/live/ukubuka.net/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/ukubuka.net/privkey.pem;

    root /usr/share/nginx/html;
    index ukubuka.html;

    location / {
        try_files /ukubuka.html =404;
    }
}

server {
    listen 80;
    listen [::]:80;

    server_name passgen.ukubuka.net;

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    http2 on;

    server_name passgen.ukubuka.net;

    ssl_certificate /etc/letsencrypt/live/ukubuka.net-0001/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/ukubuka.net-0001/privkey.pem;

    default_type text/plain;
    return 200 "В розробці\n";
}

server {
    listen 80 default_server;
    listen [::]:80 default_server;

    server_name _;

    return 444;
}

server {
    listen 443 ssl default_server;
    listen [::]:443 ssl default_server;

    server_name _;

    ssl_reject_handshake on;
}