http {
    server {
        listen 80;
        listen [::]:80;
        server_name hutei.net;
        root /usr/share/nginx/html;
        index hutei.html;
        location / {
            try_files /hutei.html =404;
        }
    }
    server {
        listen 80;
        listen [::]:80;
        server_name ukubuka.net;
        root /usr/share/nginx/html;
        index ukubuka.html;
        location / {
            try_files /ukubuka.html =404;
        }
    }
    server {
        listen 80 default_server;
        listen [::]:80 default_server;
        server_name _;
        return 444;
    }
}
